version: '3.4'

services:
  app:
    container_name: slaq
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - "../:/app"
    environment:
      SLAQ_RTM_API_TOKEN: xoxb-2451879749-380909465317-MBExdc01EGkS0zQsuBbq4I46
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
